DROP TABLE Administrateur CASCADE CONSTRAINTS;
DROP TABLE Agence CASCADE CONSTRAINTS;
DROP TABLE Agent CASCADE CONSTRAINTS;
DROP TABLE Annonce CASCADE CONSTRAINTS;
DROP TABLE Besoin CASCADE CONSTRAINTS;
DROP TABLE Categorie_Linge CASCADE CONSTRAINTS;
DROP TABLE Categorie_Service CASCADE CONSTRAINTS;
DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE Commande CASCADE CONSTRAINTS;
DROP TABLE Details_Besoin CASCADE CONSTRAINTS;
DROP TABLE Linge CASCADE CONSTRAINTS;
DROP TABLE Linge_Agence CASCADE CONSTRAINTS;
DROP TABLE Message CASCADE CONSTRAINTS;
DROP TABLE Offre CASCADE CONSTRAINTS;
DROP TABLE Pays CASCADE CONSTRAINTS;
DROP TABLE Pressing CASCADE CONSTRAINTS;
DROP TABLE Promotion CASCADE CONSTRAINTS;
DROP TABLE Proprietaire CASCADE CONSTRAINTS;
DROP TABLE Quartier CASCADE CONSTRAINTS;
DROP TABLE Role CASCADE CONSTRAINTS;
DROP TABLE Service CASCADE CONSTRAINTS;
DROP TABLE Service_Agence CASCADE CONSTRAINTS;
DROP TABLE Type_Linge CASCADE CONSTRAINTS;
DROP TABLE Type_Service CASCADE CONSTRAINTS;
DROP TABLE Utilisateur CASCADE CONSTRAINTS;
DROP TABLE Ville CASCADE CONSTRAINTS;
-- BEGIN 
 
-- FOR rec_table IN (SELECT table_name FROM cat WHERE table_name LIKE 'TTD_%')
--     LOOP
 
--         EXECUTE IMMEDIATE 'DROP TABLE '||rec_table.table_name||' CASCADE CONSTRAINTS';
 
--     END LOOP;
 
-- END;
-- /