CREATE or REPLACE FUNCTION FO_IS_NUMBER(str IN VARCHAR2) 
RETURN BOOLEAN
IS
  n NUMBER;
BEGIN
  SELECT TO_NUMBER(str) INTO n FROM DUAL;
  RETURN (true);
EXCEPTION WHEN OTHERS THEN
  RETURN (false);
END;
/