SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION verify_mail 
mail UTILISATEUR.Email%TYPE
Isexist BOOLEAN
RETURN BOOLEAN 
IS
IF(Isexist == FALSE)
{
    DBMS_OUTPUT.PUT_LINE('Desole ce mail existe deja');
}
ELSE
{
    DBMS_OUTPUT.PUT_LINE('Reussie');
}