SET serveroutput on;
CREATE OR REPLACE PACKAGE PA_AJOUT_AGENCES AS
    FUNCTION AJOUT_SERVICE_TYPE_LINGE(
        Nom_Pressing Pressing.Nom%TYPE, Lieu QUARTIER.nom%TYPE,
        Nom_CatLinge CATEGORIE_LINGE.Nom%TYPE,
        Nom_TypeLinge TYPE_LINGE.Nom%TYPE,
        
        )
    RETURN VARCHAR2;
END PA_AJOUT_AGENCES;
/
CREATE OR REPLACE PACKAGE BODY PA_AJOUT_AGENCES AS
    FUNCTION AJOUT_SERVICE_TYPE_LINGE(
        Nom_Pressing Pressing.Nom%TYPE, Lieu QUARTIER.nom%TYPE,
        Nom_CatLinge CATEGORIE_LINGE.Nom%TYPE,
        Nom_TypeLinge TYPE_LINGE.Nom%TYPE
        )
   
   END AJOUT_SERVICE_TYPE_LINGE;
END PA_AJOUT_AGENCES;
/