SET serveroutput on;
CREATE OR REPLACE PACKAGE AJOUT_CATEGORIE_SERVICE AS
    FUNCTION AJOUT_CatService(NOMCATSERVICE Categorie_Service.nom%TYPE)
    RETURN VARCHAR2;
END AJOUT_CATEGORIE_SERVICE;
/
CREATE OR REPLACE PACKAGE BODY AJOUT_CATEGORIE_SERVICE AS
    FUNCTION AJOUT_CatService (NOMCATSERVICE Categorie_Service.nom%TYPE)
   RETURN VARCHAR2 IS
    retour VARCHAR2(255);
	CURSOR turn IS
        SELECT id
        FROM Categorie_Service
        WHERE (nom=NOMCATSERVICE);
	 DONNEES VARCHAR2 (255);
   BEGIN
        OPEN turn;
        FETCH turn
        INTO DONNEES;
            IF turn%NOTFOUND THEN
                DBMS_OUTPUT.PUT_LINE('Le nom de la categorie service n''existe pas');           
            END IF;
        CLOSE turn;
        RETURN DONNEES;
   RETURN (retour);
END AJOUT_CatService;
END AJOUT_CATEGORIE_SERVICE;
/
DECLARE 
    DONNEES VARCHAR2 (255) :=AJOUT_CATEGORIE_SERVICE.AJOUT_CatService('&NOMCATSERVICE');
BEGIN
    DBMS_OUTPUT.PUT_LINE(DONNEES);
END;
/