SET serveroutput on;
CREATE OR REPLACE PACKAGE AJOUT_TYPE_SERVICE AS
    FUNCTION AJOUT_TypService(NOMTYPSERVICE Type_Service.Intitule%TYPE)
    RETURN VARCHAR2;
END AJOUT_TYPE_SERVICE;
/
CREATE OR REPLACE PACKAGE BODY AJOUT_TYPE_SERVICE AS
    FUNCTION AJOUT_TypService (NOMTYPSERVICE Type_Service.Intitule%TYPE)
   RETURN VARCHAR2 IS
    retour VARCHAR2(255);
	CURSOR turn IS
        SELECT id
        FROM Type_Service
        WHERE (Intitule=NOMTYPSERVICE);
	 DONNEES VARCHAR2 (255);
   BEGIN
        OPEN turn;
        FETCH turn
        INTO DONNEES;
            IF turn%NOTFOUND THEN
                DBMS_OUTPUT.PUT_LINE('Le nom de le type service n''existe pas');           
            END IF;
        CLOSE turn;
        RETURN DONNEES;
   RETURN (retour);
END AJOUT_TypService;
END AJOUT_Type_SERVICE;
/
DECLARE 
    DONNEES VARCHAR2 (255) :=AJOUT_TYPE_SERVICE.AJOUT_TypService('&NOMTYPSERVICE');
BEGIN
    DBMS_OUTPUT.PUT_LINE(DONNEES);
END;
/