CREATE OR REPLACE PACKAGE PA_CONSULTATION_PROMOTION AS
    PROCEDURE PO_CONSULTER_PROMOTION(id_agence AGENCE.id%TYPE);
END PA_CONSULTATION_PROMOTION;
/
CREATE OR REPLACE PACKAGE BODY PA_CONSULTATION_PROMOTION AS
END PA_CONSULTATION_PROMOTION;
/