PROMPT CREATION DES CONTRAINTES DE CLES ETRANGERES
@@CE_Administrateur
@@CE_Proprietaire
@@CE_Pressing
@@CE_Ville
@@CE_Quartier
@@CE_Agence
@@CE_Agent
@@CE_service
@@CE_Linge
@@CE_Service_Agence
@@CE_Linge_Agence
@@CE_Offre
@@CE_Promotion
@@CE_Client
@@CE_Besoin
@@CE_Details_Besoin
@@CE_Message
@@CE_Commande