SET serveroutput on;
CREATE PACKAGE PACK_PRESSING AS
FUNCTION CHECK(NOM_PRESSING Pressing.Nom%TYPE, NOM_VILLE Ville.Nom%TYPE, NOM_QUARTIER Quartier.NOM%TYPE, ID_AGENCE Agence.id%TYPE)
RETURN VARCHAR2;
END PACK_PRESSING;
CREATE PACKAGE BODY PACK_PRESSING AS
FUNCTION CHECK(NOM_PRESSING Pressing.Nom%TYPE, NOM_VILLE Ville.Nom%TYPE, NOM_QUARTIER Quartier.NOM%TYPE, ID_AGENCE Agence.id%TYPE)
RETURN VARCHAR2 IS
RUN VARCHAR2(10)
CURSOR RUN IS
SELECT p.Nom, V.Nom, q.Nom, a.id
FROM Pressing p JOIN Agence a
ON p.id=a.id_pressing
JOIN Quartier q 
ON a.id_quartier=q.id
JOIN Ville v 
ON q.id_ville=v.id
WHERE a.id=CHECK;
DONNEES VARCHAR2(10)
BEGIN
OPEN RUN
FETCH RUN
INTO DONNEES
IF RUN%NOTFOUND THEN
                    DBMS_OUTPUT.PUT_LINE('Pressing Not exist');
                ELSE
                    DBMS_OUTPUT.PUT_LINE('Pressing exist');
                END IF;
            CLOSE RUN;
            RETURN DONNEES;
    RETURN (RUN);
    END CHECK;
END PACK_PRESSING;
/
DECLARE 
DELETE FROM PRESSING WHERE id=CHECK;
END;
/