ALTER  TABLE COMMANDE 
MODIFY   id VARCHAR2 (50) NOT NULL
MODIFY   description VARCHAR2(255) NOT NULL
MODIFY  adressePayement VARCHAR2(255) NOT NULL
MODIFY addresseRamassage VARCHAR2 (50) NOT NULL
MODIFY addresseLivraison VARCHAR2(50) NOT NULL
MODIFY id_besoin VARCHAR2(50) NOT NULL
MODIFY id_agence VARCHAR2(50) NOT NULL
MODIFY dateEmissionMessage DATE NOT NULL
;