ALTER TABLE SERVICE_AGENCE    
 MODIFY   id_categorie VARCHAR2(50) NOT NULL
 MODIFY    id_agence VARCHAR2(50) NOT NULL
 MODIFY    dateAjout DATE NOT NULL
 MODIFY    id_type VARCHAR2(50) NOT NULL
 MODIFY    dateRetrait DATE NOT NULL
;