ALTER TABLE UTILISATEUR
MODIFY Id VARCHAR2(50) NOT NULL
MODIFY Nom VARCHAR2(255) NOT NULL
MODIFY Prenom VARCHAR2(255) NOT NULL
MODIFY Genre CHAR(15) NOT NULL
MODIFY Email VARCHAR2(255) NOT NULL
MODIFY Telephone NUMBER NOT NULL
MODIFY Nom_Utilisateur VARCHAR2(255) NOT NULL
MODIFY mot_de_passe VARCHAR2(90) NOT NULL;