ALTER TABLE UTILISATEUR
MODIFY Id VARCHAR2(50) NOT NULL
MODIFY Nom VARCHAR(255) NOT NULL
MODIFY Prenom VARCHAR(255) NOT NULL
MODIFY Genre CHAR(15) NOT NULL
MODIFY Email VARCHAR(255) NOT NULL
MODIFY Telephone NUMBER NOT NULL
MODIFY Nom_Utilisateur VARCHAR(255) NOT NULL
MODIFY mot_de_passe VARCHAR(90) NOT NULL;