ALTER  TABLE COMMANDE 
MODIFY   id VARCHAR2 (50) NOT NULL
MODIFY   description VARCHAR2(255) NOT NULL
MODIFY  adresse_Payement VARCHAR2(255) NOT NULL
MODIFY adresse_Ramassage VARCHAR2 (50) NOT NULL
MODIFY adresse_Livraison VARCHAR2(50) NOT NULL
MODIFY id_besoin VARCHAR2(50) NOT NULL
MODIFY id_agence VARCHAR2(50) NOT NULL
MODIFY date_Emission_Message DATE NOT NULL
;