ALTER TABLE LINGE_AGENCE
MODIFY id_categorie VARCHAR2(50) NOT NULL
MODIFY id_agence VARCHAR2(50) NOT NULL
MODIFY Date_ajout Date NOT NULL
MODIFY id_type VARCHAR2(50) NOT NULL
MODIFY  Date_retrait DATE NOT NULL
;